# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: consumerdata
  labels:
    colocation.netease.com/workload-type: service
spec:
  image:
    name: hub.c.163.com/flink/flink:1.9.1-hdfs-1
    pullPolicy: IfNotPresent
  jobManager:
    accessScope: NodePort
    ports:
      ui: 8081
      rpc: 6123
    resources:
      limits:
        memory: "4096Mi"
        cpu: "1000m"
    volumes:
    - name: consumerdata-sloth
      emptyDir: {}
    volumeMounts:
    - mountPath: /opt/flink/log
      name: consumerdata-sloth
#    nodeSelector:
#       app: flink
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: "4096Mi"
        cpu: "1000m"
    volumes:
    - name: consumerdata-sloth
      emptyDir: {}
    volumeMounts:
    - mountPath: /opt/flink/log
      name: consumerdata-sloth
#    nodeSelector:
#      app: flink
  job:
    jarFile: hdfs://slothTest/sloth/sloth/blockupload/dbdf751b54eb11b0699fef07740cf7b2/kafkaDemo19-1.0-SNAPSHOT.jar
    filePath: ["hdfs://slothTest/sloth/sloth/blockupload/6df0fde9feeb2b73d669c1de91939b1e/fastjson-1.2.66.jar"]
    className: com.netease.java.TopSpeedWindowing
    args: ["--input-topic", "k8s-test-data","--bootstrap.servers","sloth-test0.dg.163.org:9092,sloth-test1.dg.163.org:9092,sloth-test2.dg.163.org:9092",
           "--group.id","consumer-5","--output-topic", "k8s-test-output"]
    parallelism: 1
    volumes:
    - name: consumerdata-sloth
      emptyDir: {}
    - name: init-job
      emptyDir: {}
    volumeMounts:
    - mountPath: /opt/flink/log
      name: consumerdata-sloth
    - mountPath: /opt/flink/job
      name: init-job
    env:
      - name: FLINK_JOB_FILES_URI
        value: "hdfs://slothTest/sloth/sloth/blockupload/6df0fde9feeb2b73d669c1de91939b1e/fastjson-1.2.66.jar"
#    nodeSelector:
#      app: flink
    initContainers:
     - name: hdfs-downloader
       image: hub.c.163.com/flink/flink-init:0.0.5
       pullPolicy: Always
       volumeMounts:
       - mountPath: /opt/flink/job
         name: init-job
       env:
         - name: FLINK_JOB_JAR_URI
           value: "hdfs://slothTest/sloth/sloth/blockupload/dbdf751b54eb11b0699fef07740cf7b2/kafkaDemo19-1.0-SNAPSHOT.jar"
         - name: FLINK_JOB_FILES_URI
           value: "hdfs://slothTest/sloth/sloth/blockupload/6df0fde9feeb2b73d669c1de91939b1e/fastjson-1.2.66.jar"
  env:
    - name: UUID
    - value: test
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
    high-availability: zookeeper
    high-availability.zookeeper.quorum: 10.178.4.196:2181
    high-availability.storageDir: hdfs://slothTest/user/sloth/HA/
    high-availability.cluster-id: "consumerdata"
    high-availability.jobmanager.port: "6123"
    high-availability.zookeeper.path.root: /sloth-flink-k8s
    restart-strategy: failure-rate
    restart-strategy.failure-rate.max-failures-per-interval: "5000"
    restart-strategy.failure-rate.failure-rate-interval: 6 min
    restart-strategy.failure-rate.delay: 1 s
    state.backend: rocksdb
    state.backend.incremental: "true"
    #filesystem to store checkpoint meta data (when external checkpoint enabled.)
    state.checkpoints.dir: hdfs://slothTest/user/sloth/sloth-fs-checkpoints/meta/1_7
    #filesystem to store checkpoint data
    state.backend.fs.checkpointdir: hdfs://slothTest/user/sloth/sloth-fs-checkpoints/cpk/1_7
    state.backend.rocksdb.localdir: /opt/flink/data
    metrics.reporters: influxdb
    metrics.reporter.influxdb.class: org.apache.flink.metrics.influxdb.InfluxdbReporter
    metrics.reporter.influxdb.host: sloth-tsdb0.dg.163.org,sloth-tsdb1.dg.163.org,sloth-tsdb2.dg.163.org
    metrics.reporter.influxdb.port: "8091"
    metrics.reporter.influxdb.db: flink-test-V2
    metrics.reporter.influxdb.username: flink-metrics
    metrics.reporter.influxdb.password: sloth1234
    metrics.reporter.influxdb.connectTimeout: "100000"
    metrics.reporter.influxdb.writeTimeout: "10000"
    metrics.reporter.influxdb.consistency: ANY
